import {
  Column,
  CreateDateColumn,
  Entity,
  ManyToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';
import { ApiProperty } from '@nestjs/swagger';
import { User } from '../../users/entities/user.entity';

@Entity('notes')
export class Note {
  @ApiProperty({
    description: 'Unique note identifier',
    example: 1,
  })
  @PrimaryGeneratedColumn()
  id: number;

  @ApiProperty({
    description: 'Note timestamp',
    example: '2023-12-03T10:30:00',
  })
  @Column({ type: 'varchar', length: '255' })
  time: string;

  @ApiProperty({
    description: 'Note content',
    example: 'This is an important note',
  })
  @Column({ type: 'text' })
  content: string;

  @ApiProperty({
    description: 'Note importance level',
    enum: ['medium', 'critical'],
    example: 'medium',
  })
  @Column({
    type: 'enum',
    enum: ['medium', 'critical'],
    default: 'medium',
  })
  importance: 'medium' | 'critical';

  @ApiProperty({
    description: 'Indicates if the note was generated by AI',
    example: false,
  })
  @Column({ type: 'boolean', default: false })
  isAiGenerated: boolean;

  @ApiProperty({
    description: 'User who created the note',
    type: () => User,
  })
  @ManyToOne(() => User, (user) => user.notes, { onDelete: 'CASCADE' })
  user: User;

  @ApiProperty({
    description: 'User ID',
    example: 1,
  })
  @Column()
  userId: number;

  @ApiProperty({
    description: 'Note creation timestamp',
    example: '2023-12-03T00:00:00.000Z',
  })
  @CreateDateColumn()
  createdAt: Date;

  @ApiProperty({
    description: 'Note last update timestamp',
    example: '2023-12-03T00:00:00.000Z',
  })
  @UpdateDateColumn()
  updatedAt: Date;
}
